# Generated by Django 5.2.7 on 2025-11-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('Enviar', 'Tipo enviar'), ('Devolver', 'Tipo devolver')], max_length=15, verbose_name='Categoria')),
                ('ubicacion', models.CharField(max_length=30, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
