# Generated by Django 5.2.7 on 2025-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7, verbose_name='Número')),
                ('herramienta_codigo', models.CharField(max_length=20, verbose_name='Codigo de herramientas')),
                ('responsable', models.CharField(max_length=15, verbose_name='Responsable')),
                ('fecha_salida', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
