# Generated by Django 5.2.7 on 2025-11-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prestamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Estado Activo'), ('Devuelto', 'Estado Devuelto'), ('Vencido', 'Estado Vencido'), ('Cancelado', 'Estado Cancelado')], default='Activo', max_length=50),
        ),
    ]
