# Generated by Django 5.2.7 on 2025-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_herramientas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En préstamo', 'En préstamo'), ('En mantenimiento', 'En mantenimiento'), ('Inactivo', 'Inactivo')], default='Disponible', max_length=50),
        ),
    ]
