# Generated by Django 5.2.7 on 2025-11-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_herramientas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
