# Generated by Django 5.2.7 on 2025-11-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_herramientas_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientas',
            name='activo',
        ),
    ]
