# Generated by Django 5.2.7 on 2025-11-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_herramientas_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Devolución'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fecha_esperada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Esperada'),
        ),
    ]
