# Generated by Django 5.2.7 on 2025-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prestamos_fecha_devolucion_prestamos_fecha_esperada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
