# Generated by Django 5.2.7 on 2025-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='first_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa_del_vehiculo', models.CharField(max_length=200)),
                ('Valor_del_cargue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tipo_de_carga', models.CharField(max_length=100)),
                ('Vencimiento_de_soat', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
