# Generated by Django 5.2.7 on 2025-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_project',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='first_project',
            name='Placa_del_vehiculo',
            field=models.CharField(max_length=7),
        ),
    ]
