# Generated by Django 5.2.7 on 2025-10-10 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_firstproject_tipo_de_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstproject',
            name='Placa_del_vehiculo',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Formato: AAA-123 (3 letras, guión, 3 números)', regex='^[A-Z]{3}-\\d{3}$')], verbose_name='Placa del vehículo'),
        ),
    ]
