# Generated by Django 5.2.7 on 2025-10-07 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_first_project_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa_del_vehiculo', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener el formato AAA-123, solo letras mayúsculas, números y el guion para la separacion de letras y numero.', regex='^[A-Z]{3}-\\d{3}$')], verbose_name='Placa del vehículo')),
                ('Valor_del_cargue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tipo_de_carga', models.CharField(max_length=100)),
                ('Vencimiento_de_soat', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='first_project',
        ),
    ]
