# Generated by Django 5.2.7 on 2025-10-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_firstproject_delete_first_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstproject',
            name='Tipo_de_carga',
            field=models.CharField(choices=[('General', 'Carga general'), ('Peligrosa', 'Carga peligrosa'), ('Refrigerada', 'Carga refrigerada'), ('Voluminosa', 'Carga voluminosa'), ('Liquida', 'Carga líquida')], default='General', max_length=20, verbose_name='Tipo de carga'),
        ),
    ]
