# Generated by Django 5.2.7 on 2025-10-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_firstproject_placa_del_vehiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstProject',
            new_name='Project_cargues',
        ),
    ]
