# Generated by Django 5.2.8 on 2025-11-17 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa_del_vehiculo', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Formato: AAA-123 (3 letras, guión, 3 números)', regex='^[A-Z]{3}-\\d{3}$')], verbose_name='Placa del vehículo')),
                ('Valor_del_cargue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tipo_de_carga', models.CharField(choices=[('General', 'Carga general'), ('Peligrosa', 'Carga peligrosa'), ('Refrigerada', 'Carga refrigerada'), ('Voluminosa', 'Carga voluminosa'), ('Liquida', 'Carga líquida')], default='General', max_length=20, verbose_name='Tipo de carga')),
                ('Vencimiento_de_soat', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
